name: (Azure) Deploy API

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'         

      - name: Install dependencies
        run: npm ci

      - name: Build NestJS API
        run: npx nx build api --configuration production

      - name: Zip API build output
        run: |
          cd dist/apps/api
          zip -r ../../release-api.zip .
        shell: bash

      - name: Upload artifact for deployment
        uses: actions/upload-artifact@v4
        with:
          name: api-artifact
          path: dist/release-api.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: api-artifact

      - name: Unzip API package
        run: |
          mkdir -p dist/apps/api
          unzip release-api.zip -d dist/apps/api

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_946D17F005F743C28BF30FCE08C32B65 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_3F83878ACC8241898C68359F0C920E12 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_C6D0D34EB0604B19A67B9C0F2B7D00C0 }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'krdrive-api'
          slot-name: 'Production'
          package: dist/apps/api       # point at the folder containing main.js
